### ISSUE TITLE
Add types for consuming the library in TS

### ISSUE THREAD

**Issue by DillonSadofsky** [TehShrike/financial-number#15]
There doesn't seem to be an `@types/financial-number` as a separate project or a .d.ts file shipped with the project.  Reasonable, but it makes it harder to import into TS code and consume it (generally have to turn off some linting/warning issues and treat everything as `any`).  I imagine the surface area of the module is small enough to export just a couple types without having to write any TS.  I'll probably try to add some types locally for the project, and if I get something working, I'll post it in case you want to use any of it as an official type decoration either in-module or as a separate `@types`.

**Comment by TehShrike** [comment]
Oh yeah – I actually wanted to get `financial-number` and its dependency `financial-arithmetic-functions` converted to TypeScript themselves, but still need to add a build step to [this branch](https://github.com/TehShrike/financial-arithmetic-functions/tree/typescript).

**Comment by TehShrike** [comment]
financial-number has been converted to TypeScript as of 4.0.0 https://github.com/TehShrike/financial-number/commit/85fb8bd6ec24fcf7a053b67a1f9032652c0b57c6

(it should still be backwards compatible, the major version bump is just for paranoia/caution)

**Comment by DillonSadofsky** [comment]
Nice. Got too busy to wrangle this myself and had a couple errors because of it. These types should help with autocomplete in vs code. Cheers
